server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/basement?useSSL=false&useUnicode=true&characterEncoding=UTF-8&servertime=UTC&serverTimezone=GMT%2B8
        username: root
        password: 123456
        # 使用Druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            filters: stat
            maxActive: 20
            initialSize: 1
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
            username: admin
            password: admin
    # 404交给异常处理器处理
    mvc:
        throw-exception-if-no-handler-found: true
    # 404交给异常处理器处理
    resources:
        add-mappings: false
    redis:
        # Redis数据库索引（默认为0）
        database: 0
        # Redis服务器地址
        host: 127.0.0.1
        # Redis服务器连接 端口
        port: 6379
        # Redis服务器连接密码（默认为空）如果没有配置密码就不要写这个属性了
        password: redis
        #连接池
        lettuce:
            pool:
                #连接池最大连接数（使用负值表示没有限制）
                max-active: 8
                #连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: 60000
                #连接池中的最大空闲连接
                max-idle: 8
                #连接池中的最小空闲连接
                min-idle: 0
        #连接超时时间（毫秒）
        timeout: 10000

        # 集群配置
#        cluster:
#            nodes: 127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384,127.0.0.1:6385,127.0.0.1:6386
#            # 最大重定向次数
#            max-redirects: 2

#mybatis
mybatis-plus:
    global-config:
        db-config:
            #主键类型、参考: https://mp.baomidou.com/guide/annotation.html#tableid
            id-type: auto


# jwt
jwt:
    shared-lock:
        # 是否开启验证 Header中的Authorization
        open: false
        # JWT认证加密私钥(Base64加密) Api@Login(Auth}
        secret: QXBpQExvZ2luKEF1dGh9
        # AccessToken过期时间-5分钟-5*60(秒为单位)
        expire: 1200
        # RefreshToken过期时间-30分钟-30*60(秒为单位)
        refreshExpire: 1800
        # Header中的Authorization字段
        headerKey: Authorization
        # Authorization: Bearer; <token>
        tokenPrefix: Bearer;

logging:
    level.root: info
    level.com.eyxyt.basement: debug
    # Debug打印SQL
    level.com.wang.mapper: debug